name: Azure Storage Account Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Storage Account
      uses: azure/CLI@v1
      with:
        azcliversion: '2.28.0'
        inlineScript: |
          az storage account create \
          --name mystorageaccount \
          --resource-group myresourcegroup \
          --location eastus \
          --sku Standard_LRS \
          --kind StorageV2
